version: '2'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - TZ=Asia/Taipei
    volumes:
      - ./data/db:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    hostname: graylog.elastic
    environment:
      - http.host=0.0.0.0
      - transport.host=elasticsearch
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Taipei
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - /var/lib/elasticsearch:/var/lib/elasticsearch
      - /var/log/elasticsearch:/var/log/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://127.0.0.1:9200
      - ELASTICSEARCH_HOSTS=elasticsearch
      - TZ=Asia/Taipei
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 514:514
      - 514:514/udp
